# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- job:
    name: pod-tls-sidecar-go-test
    parent: golang-go-test
    vars:
      go_version: "1.22.6"
      go_package_dir: "..."

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - pod-tls-sidecar-go-test
    gate:
      jobs:
        - pod-tls-sidecar-go-test
